import type { CaseStudy } from "./types";

export const caseStudies: CaseStudy[] = [
  {
    slug: "pg-sales-operations",
    tier: "flagship",
    homepage: {
      title: "Hệ thống quản lý doanh số Interdist",
      summary: "Tập hợp dữ liệu bán hàng, quản lý chỉ tiêu và tạo báo cáo trong cùng một ứng dụng.",
      role: "Interdist · Dữ liệu & sản phẩm · Bán thời gian",
      evidence: "Nhập liệu, theo dõi kết quả và quản trị dữ liệu",
      cta: "Xem case Interdist",
    },
    scopeLabel: "Dữ liệu, ứng dụng và quy trình sử dụng",
    title: "Hệ thống quản lý doanh số Interdist",
    proves: "Phụ trách xây hệ thống từ yêu cầu nghiệp vụ đến ứng dụng, hướng dẫn sử dụng và bàn giao.",
    client: "Interdist",
    clientNote: "Bán thời gian, làm từ xa, song song với công việc chính tại GHN",
    role: "Làm rõ nhu cầu, tổ chức dữ liệu, xây ứng dụng và hỗ trợ triển khai",
    period: "T5/2026 - nay",
    oneLiner: "Ứng dụng nội bộ phục vụ theo dõi doanh số P&G: nhận file bán hàng, kiểm tra dữ liệu, tính mức đạt chỉ tiêu và xuất báo cáo theo vùng, kênh, cửa hàng và sản phẩm.",
    accent: "navy",
    keyResult: {
      value: "Một hệ thống cho cả luồng báo cáo doanh số",
      label: "Từ file bán hàng đến báo cáo quản lý, có công cụ cập nhật giá, chỉ tiêu và cửa hàng",
      verified: true,
    },
    context: [
      "Dữ liệu bán hàng, bảng giá, chỉ tiêu và danh sách cửa hàng được quản lý qua nhiều file. Mỗi kỳ báo cáo cần ghép các nguồn này để biết vùng nào đạt chỉ tiêu, cửa hàng nào cần theo dõi và sản phẩm nào đang bán tốt.",
      "Nhu cầu vì vậy gồm cả theo dõi kết quả lẫn quản lý dữ liệu đầu vào. Người phụ trách cần tự cập nhật file và cấu hình trong app, đồng thời truy lại các lần thay đổi khi số liệu có chênh lệch.",
    ],
    decisions: [
      {
        problem: "Quản lý dữ liệu cùng nơi xem báo cáo",
        why: "Doanh số thay đổi mỗi ngày; giá, chỉ tiêu và phân công cửa hàng cũng thay đổi theo từng kỳ. Nếu mọi cập nhật đều cần sửa code, đội sử dụng sẽ khó tự vận hành hệ thống.",
        decision: "Đưa nhập file, quản lý giá, chỉ tiêu, cửa hàng, sản phẩm và phân công vào cùng ứng dụng. Người có quyền có thể cập nhật dữ liệu, xem lịch sử nhập và xuất lại file để đối chiếu.",
        term: "Quản trị dữ liệu ngay trong ứng dụng",
      },
      {
        problem: "Một thay đổi cấu hình có thể làm báo cáo ra số khác",
        why: "Giá phải khớp thời điểm bán hàng. Chỉ tiêu ngày cần phản ánh lịch bán của từng cửa hàng. Dùng một cách tính chung cho mọi kỳ dễ làm sai doanh thu hoặc mức đạt chỉ tiêu.",
        decision: "Quản lý giá theo thời gian hiệu lực và phân bổ chỉ tiêu tháng theo lịch bán hàng. Các điều chỉnh chỉ tiêu ngày có bản xem trước tác động, lịch sử thay đổi và cơ chế hoàn tác theo lô.",
        term: "Quy tắc tính số có thể kiểm tra lại",
      },
      {
        problem: "Nhập nhầm file có thể thay cả một kỳ dữ liệu",
        why: "File mới có thể chứa mã không khớp, sai ngày hoặc sai phạm vi cửa hàng. Cần biết phần dữ liệu nào sẽ bị thay trước khi xác nhận.",
        decision: "Kiểm tra file và hiển thị phạm vi, số liệu trước và sau khi nhập. Tách bước xem trước khỏi bước ghi dữ liệu; các lỗi được trả về để người dùng sửa và kiểm tra lại.",
        term: "Xem trước và xác nhận phạm vi thay đổi",
      },
    ],
    ownership: {
      owned: [
        "Làm việc với người sử dụng để xác định cần xem gì, cách tính số và quy trình cập nhật dữ liệu.",
        "Tổ chức dữ liệu bán hàng, giá, chỉ tiêu, cửa hàng và sản phẩm để các báo cáo dùng chung cách tính.",
        "Xây ứng dụng, gồm dashboard, nhập và xuất file, công cụ quản trị dữ liệu và phân quyền tài khoản.",
        "Kiểm tra đầu ra, xử lý phản hồi, viết hướng dẫn và chuẩn bị tài liệu bàn giao kỹ thuật.",
      ],
      notOwned: [
        "Dữ liệu nguồn và quyết định kinh doanh do Interdist cung cấp, xác nhận.",
      ],
    },
    results: [
      { label: "Theo dõi kinh doanh", value: "Doanh số, chỉ tiêu và mức đạt trên cùng hệ thống", method: "Có bộ lọc theo kỳ, vùng và kênh; xem chi tiết theo cửa hàng và sản phẩm. Quy mô dữ liệu thay đổi theo từng kỳ nhập.", verified: true },
      { label: "Quy trình sử dụng", value: "Nhập file, quản lý dữ liệu và xuất báo cáo ngay trong app", method: "Người có quyền có thể cập nhật giá, chỉ tiêu và danh mục, kiểm tra lịch sử nhập rồi xuất báo cáo theo phạm vi đang xem.", verified: true },
      { label: "Thời gian tổng hợp", value: "Ước tính giảm khoảng 40-60 giờ/tháng", method: "Ước tính từ công việc tổng hợp của 3-4 người phụ trách. Chưa có đo thời gian trước và sau để xác nhận mức giảm thực tế.", verified: false },
    ],
    reflection: [
      "Ở giai đoạn đầu, dashboard được dựng trước khi cách tính chỉ tiêu được thống nhất đầy đủ, dẫn tới phải làm lại phần tính toán. Kinh nghiệm rút ra là xác nhận định nghĩa và ví dụ dữ liệu trước khi xây màn hình.",
      "Cần đo thời gian của một kỳ tổng hợp ngay từ đầu. Thiếu mốc so sánh khiến phần tiết kiệm công sức vẫn chỉ là ước tính dù hệ thống đã có đầu ra cụ thể.",
    ],
    features: [
      { title: "Theo dõi doanh số", description: "Xem kết quả, xu hướng và mức đạt chỉ tiêu; tìm vùng, cửa hàng hoặc sản phẩm cần kiểm tra thêm.", icon: "chart" },
      { title: "Cập nhật dữ liệu", description: "Nhập và xuất Excel/CSV, xem trước phạm vi thay đổi và truy lại lịch sử nhập file.", icon: "file-spreadsheet" },
      { title: "Quản lý thông tin bán hàng", description: "Cập nhật giá, chỉ tiêu, lịch bán, danh sách cửa hàng, sản phẩm và phân công người phụ trách.", icon: "settings" },
      { title: "Báo cáo và tài khoản", description: "Xuất báo cáo để chia sẻ; cấp quyền sử dụng và quản trị theo vai trò.", icon: "users" },
    ],
    flowHeading: "Từ file bán hàng đến báo cáo quản lý",
    flow: {
      nodes: [
        { id: "file", label: "File bán hàng", sublabel: "Excel / CSV" },
        { id: "check", label: "Kiểm tra và xem trước", sublabel: "phạm vi và chênh lệch dữ liệu" },
        { id: "data", label: "Dữ liệu đã xác nhận", sublabel: "kết hợp giá, chỉ tiêu và thông tin cửa hàng" },
        { id: "view", label: "Dashboard và báo cáo", sublabel: "theo kỳ, vùng, kênh và sản phẩm" },
      ],
      edges: [{ from: "file", to: "check" }, { from: "check", to: "data" }, { from: "data", to: "view" }],
    },
    stack: [
      { group: "Ứng dụng", items: ["React", "TypeScript", "Vite", "Tailwind CSS"] },
      { group: "Dữ liệu", items: ["SQL", "PostgreSQL / Supabase", "Excel / CSV"] },
      { group: "Triển khai", items: ["Vercel", "Google OAuth", "AI-assisted coding"] },
    ],
    media: [
      { id: "hero-shot", kind: "image", brief: "Giao diện dashboard với dữ liệu minh hoạ.", src: "/case-pg-dashboard.png", width: 1838, height: 907, alt: "Dashboard doanh số với KPI, xu hướng và chi tiết theo vùng", isDemoData: true, caption: "Theo dõi doanh số và mức đạt chỉ tiêu theo vùng. Giao diện thật, dữ liệu minh hoạ." },
      { id: "import-flow", kind: "image", brief: "Bản xem trước khi thay dữ liệu bán hàng.", src: "/case-pg-import-preview.png", width: 780, height: 595, alt: "Bản xem trước so sánh dữ liệu hiện có và sau khi nhập file", isDemoData: true, caption: "Kiểm tra phạm vi và chênh lệch trước khi xác nhận nhập file. Dữ liệu minh hoạ." },
      { id: "target-preview", kind: "image", brief: "Điều chỉnh chỉ tiêu ngày và xem tác động.", src: "/case-pg-target-preview.png", width: 1086, height: 611, alt: "Lịch điều chỉnh chỉ tiêu ngày với bảng so sánh trước và sau", isDemoData: true, caption: "Xem tác động của điều chỉnh chỉ tiêu trước khi lưu. Dữ liệu minh hoạ." },
    ],
  },
  {
    // Giữ slug cũ để các liên kết đã chia sẻ vẫn mở đúng case.
    slug: "kas-shopee-performance",
    tier: "flagship",
    homepage: {
      title: "GHN Ops Pulse",
      summary: "Master dashboard cho cả team xem lấy hàng, giao hàng và đơn tồn, kèm báo cáo tự gửi vào nhóm Telegram mỗi sáng.",
      role: "Giao Hàng Nhanh · Dữ liệu & ứng dụng",
      evidence: "Dùng hằng ngày; báo cáo tự động tới nhóm lãnh đạo",
      cta: "Xem case Ops Pulse",
    },
    scopeLabel: "Master dashboard vận hành và báo cáo tự động qua Telegram",
    title: "GHN Ops Pulse",
    proves: "Phục vụ mọi người trong team, từ vận hành đến lãnh đạo, ngay trên màn hình và trong nhóm chat hằng ngày.",
    client: "Giao Hàng Nhanh (GHN)",
    clientNote: "Xây dựng trong công việc chính, dùng chung cho cả team",
    role: "Xây ứng dụng, tổ chức dữ liệu phục vụ báo cáo, dựng luồng báo cáo tự động và duy trì sau triển khai",
    period: "2026 - nay",
    oneLiner: "Dashboard tổng hợp chỉ số lấy hàng, giao hàng và đơn chưa hoàn thành cho mọi người trong team, từ nhân viên vận hành đến lãnh đạo. Mỗi sáng hệ thống tự chụp các bảng báo cáo và gửi vào nhóm Telegram, kèm đoạn nhận xét về ngày hôm trước.",
    accent: "blue",
    keyResult: { value: "Một dashboard dùng chung, báo cáo tự gửi mỗi sáng", label: "Cả team xem cùng một bộ số liệu; nhóm Telegram của lãnh đạo nhận báo cáo tự động hằng ngày", verified: true },
    context: [
      "Theo dõi vận hành mỗi ngày cần cả bức tranh tổng thể lẫn chi tiết tại từng đơn vị. Một tỷ lệ toàn quốc có thể che mất vùng đang giảm hiệu suất hoặc hub đang phát sinh nhiều đơn trễ. Người làm vận hành, người quản lý và lãnh đạo cần nhìn cùng một bộ số, chỉ khác mức độ đi sâu.",
      "Dashboard tập hợp các bảng theo dõi vào cùng một nơi, giúp mọi người đi từ chỉ số tổng quan xuống khu vực cần kiểm tra. Kết quả còn phải tới được nơi mọi người thật sự đọc: cuộc họp và nhóm chat hằng ngày, nên báo cáo được gửi tự động thay vì chờ ai đó chụp và gửi.",
    ],
    decisions: [
      {
        problem: "Xem nhanh tình hình, rồi biết cần kiểm tra ở đâu",
        why: "Chỉ số tổng hợp cho biết hiệu suất chung, nhưng người dùng còn cần biết đơn vị nào đang dưới chỉ tiêu và lượng đơn bị ảnh hưởng.",
        decision: "Đặt KPI, xu hướng và danh sách hub cần ưu tiên ở trang tổng quan. Từ đó mở chi tiết theo miền, vùng và hub, dùng cùng phạm vi khách hàng, ngày và loại hub đã chọn.",
        term: "Từ tổng quan đến chi tiết",
      },
      {
        problem: "Báo cáo gửi tự động dễ lệch với dashboard",
        why: "Bản đầu của luồng gửi tự dựng bảng riêng. Mỗi lần dashboard đổi, như thêm vùng, đổi thứ tự hay thêm cột, phải sửa thêm ở nơi thứ hai, và hai nơi sớm muộn sẽ ra hai con số khác nhau.",
        decision: "Cho luồng tự động chụp chính dashboard thay vì dựng bảng thứ hai. Ảnh gửi đi luôn là thứ người dùng thấy trên màn hình. Liên kết chụp dùng mã tạm hết hạn sau 30 phút, khoá bí mật dài hạn không xuất hiện trong đường dẫn.",
        term: "Một nguồn hiển thị cho cả web và Telegram",
      },
      {
        problem: "Số liệu cần đi cùng luồng trao đổi của người dùng",
        why: "Kết quả được bàn trong họp và nhóm chat. Việc chụp, cắt và ghép bảng thủ công làm chậm quá trình chia sẻ, nhất là khi bảng dài.",
        decision: "Bổ sung chế độ toàn màn hình và copy bảng thành ảnh để dán vào nhóm. Khi cần đối chiếu số thô, có thể xuất CSV theo bộ lọc.",
        term: "Chia sẻ ngay từ màn hình đang xem",
      },
      {
        problem: "Nguồn nội bộ bị chặn chia sẻ ra ngoài",
        why: "Đường đọc CSV công khai từ Google Sheet ngừng hoạt động khi chính sách Workspace chặn chia sẻ. App cần một cách nhận dữ liệu phù hợp với quyền truy cập của nguồn.",
        decision: "Dùng Apps Script tại file nguồn để đồng bộ sang cơ sở dữ liệu phục vụ app. Giữ nơi cập nhật dữ liệu hiện có, đồng thời tách việc đồng bộ khỏi việc người dùng mở báo cáo.",
        term: "Đồng bộ nguồn và phục vụ báo cáo ở hai bước riêng",
      },
    ],
    ownership: {
      owned: [
        "Chuyển nhu cầu theo dõi của team thành màn hình tổng quan, bảng chi tiết và bộ lọc.",
        "Xây luồng đồng bộ, tổ chức dữ liệu phục vụ app và kiểm tra cách tổng hợp chỉ số.",
        "Xây giao diện, xác thực, phân quyền, nhật ký truy cập và công cụ xuất/chia sẻ báo cáo.",
        "Dựng luồng báo cáo tự động gửi Telegram mỗi sáng, gồm các bảng và đoạn nhận xét ngày hôm trước.",
        "Duy trì ứng dụng, xử lý phản hồi và mở rộng chức năng theo nhu cầu vận hành.",
      ],
      notOwned: [
        "Định nghĩa KPI gốc và dữ liệu nguồn thuộc quy trình chung của GHN.",
        "Quyết định điều hành và xử lý các đơn vị thuộc trách nhiệm của quản lý, vận hành.",
      ],
    },
    results: [
      { label: "Sử dụng thực tế", value: "Cả team dùng hằng ngày; nhóm lãnh đạo nhận báo cáo tự động", method: "Phục vụ xem tình hình vận hành, mở chi tiết vùng/hub và nhận báo cáo qua Telegram mỗi sáng. Chưa có thống kê riêng về số người dùng và tần suất truy cập để công bố.", verified: true },
      { label: "Báo cáo tự động", value: "9 bảng và nhận xét ngày hôm trước mỗi sáng", method: "Luồng tự động chụp chính dashboard rồi gửi từng ảnh theo thứ tự, sau đó là đoạn nhận xét so sánh ngày gần nhất với ngày trước đó.", verified: true },
      { label: "Phạm vi theo dõi", value: "Lấy hàng, giao hàng và đơn chưa hoàn thành", method: "Có KPI tổng quan, chi tiết vùng/hub, chỉ số ca 1 theo tuyến và bảng xếp hạng hiệu suất. Leadtime và Insight còn đang phát triển.", verified: true },
    ],
    reflection: [
      "Trang tổng quan cần dẫn người xem tới vùng hoặc hub cần kiểm tra. Chỉ hiển thị tỷ lệ chung chưa đủ cho một cuộc trao đổi điều hành.",
      "Khi báo cáo đã tự đến nhóm chat mỗi sáng, độ ổn định của đồng bộ trở thành một phần của sản phẩm. Một ngày dữ liệu chậm là một ngày cả nhóm nhìn số cũ mà không biết, nên cách báo trạng thái và thông báo thay đổi cũng quan trọng như bản thân con số.",
    ],
    features: [
      { title: "Tổng quan cho cả team", description: "KPI, xu hướng và hub cần ưu tiên trong phạm vi đang chọn.", icon: "chart" },
      { title: "Tra cứu theo đơn vị", description: "Mở từ toàn quốc xuống miền, vùng và hub; so sánh chỉ số giữa các kỳ.", icon: "search" },
      { title: "Báo cáo tự động qua Telegram", description: "Mỗi sáng tự chụp các bảng từ dashboard và gửi vào nhóm, kèm nhận xét ngày hôm trước.", icon: "image" },
      { title: "Chia sẻ và theo dõi", description: "Xem toàn màn hình, copy bảng thành ảnh, xuất CSV và bảng xếp hạng hiệu suất.", icon: "list" },
    ],
    flowHeading: "Từ nguồn dữ liệu đến màn hình và nhóm chat",
    flow: {
      nodes: [
        { id: "source", label: "Dữ liệu nguồn nội bộ" },
        { id: "sync", label: "Đồng bộ dữ liệu phục vụ app" },
        { id: "dashboard", label: "Dashboard dùng chung", sublabel: "từ tổng quan xuống vùng và hub" },
        { id: "telegram", label: "Báo cáo Telegram mỗi sáng", sublabel: "chụp từ chính dashboard" },
      ],
      edges: [{ from: "source", to: "sync" }, { from: "sync", to: "dashboard" }, { from: "dashboard", to: "telegram" }],
    },
    stack: [
      { group: "Ứng dụng", items: ["React", "Vite", "AI-assisted coding"] },
      { group: "Dữ liệu", items: ["SQL", "Supabase", "Google Apps Script"] },
      { group: "Báo cáo tự động", items: ["n8n", "Telegram"] },
      { group: "Triển khai", items: ["Vercel", "Google OAuth"] },
    ],
    media: [
      { id: "matrix-overview", kind: "image", brief: "Ảnh minh hoạ giao diện ở phiên bản trước.", src: "/case-kas-shopee-matrix.png", width: 1800, height: 1000, alt: "KPI và bảng tỷ lệ đúng giờ theo miền, vùng trong dashboard vận hành", isDemoData: true, wide: true, caption: "KPI và chi tiết theo miền, vùng. Ảnh phiên bản trước của app, dữ liệu minh hoạ." },
      { id: "hub-drill", kind: "image", brief: "Bảng chi tiết vùng/hub và nút copy ảnh.", src: "/case-kas-shopee-hub-drill.png", width: 1800, height: 960, alt: "Bảng mở rộng tới từng hub với nút copy bảng thành ảnh", isDemoData: true, wide: true, caption: "Mở chi tiết tới từng hub và copy bảng để chia sẻ. Ảnh phiên bản trước, dữ liệu minh hoạ." },
      { id: "access-log", kind: "image", brief: "Nhật ký truy cập và người đang online.", src: "/case-kas-shopee-access-log.png", width: 1800, height: 1090, alt: "Trang quản trị hiển thị tài khoản truy cập, số lượt và người đang online", isDemoData: true, caption: "Theo dõi tài khoản và lượt truy cập. Ảnh phiên bản trước, dữ liệu minh hoạ." },
    ],
  },
  {
    slug: "cod-screening",
    tier: "deep",
    homepage: {
      title: "Rà soát đơn nghi chiếm dụng COD",
      summary: "Module AI trong GHN Ops Pulse: tự cập nhật danh sách đơn thu hộ đáng kiểm tra, có mức nghi ngờ và theo dõi xử lý, thay vì một bài phân tích chạy tay.",
      role: "Giao Hàng Nhanh · Dữ liệu & ứng dụng",
      evidence: "Chạy theo lịch trong dashboard; danh sách sàng lọc, không phải kết luận",
      cta: "Xem case rà soát COD",
      badge: { label: "AI", aria: "Có dùng AI để chấm điểm tin nhắn" },
    },
    scopeLabel: "Module AI trong GHN Ops Pulse",
    title: "Rà soát đơn nghi chiếm dụng COD",
    proves: "Biến một bài phân tích chạy một lần thành module chạy theo lịch, có phân quyền, theo dõi xử lý và chấm điểm bằng AI.",
    client: "Giao Hàng Nhanh (GHN)",
    clientNote: "Trong công việc chính, theo yêu cầu của quản lý. Chi tiết nhận diện được lược bỏ có chủ đích.",
    role: "Định nghĩa tín hiệu, viết truy vấn, xây module rà soát và luồng ghi nhận xử lý trong GHN Ops Pulse",
    period: "2026 - nay",
    oneLiner: "Một số đơn thu hộ (COD) có dấu hiệu bị chiếm dụng: người giao đã nhận tiền nhưng cập nhật chậm hoặc cập nhật sai để giữ lại. Hệ thống chỉ ghi trạng thái cuối nên không chứng minh được. Module này nằm ngay trong GHN Ops Pulse, tự cập nhật danh sách đơn đáng kiểm tra theo mức nghi ngờ, kèm phần theo dõi xử lý, và nói rõ danh sách chưa phải kết luận.",
    accent: "amber",
    keyResult: {
      value: "Từ phân tích chạy tay thành module chạy theo lịch",
      label: "Danh sách đơn đáng kiểm tra tự cập nhật trong dashboard, có AI chấm điểm, phân quyền và theo dõi xử lý; chưa phải kết luận vi phạm",
      verified: true,
    },
    context: [
      "Với đơn thu hộ, người giao có thể đã nhận tiền từ người mua nhưng chưa cập nhật lên hệ thống ngay. Có người giữ vài ngày để xoay vòng rồi vẫn nộp; có người cập nhật giao không thành công hoặc chuyển hoàn để giữ hẳn. Đơn cuối cùng có thể vẫn mang trạng thái giao thành công, nên dữ liệu trạng thái không trả lời được câu hỏi.",
      "Dấu vết nằm ở chỗ các nguồn không khớp nhau: lý do thất bại, nhật ký cuộc gọi, khoảng cách giữa lần gán giao và lần kết thúc giao, vị trí khi cập nhật. Ban đầu đây là một bài phân tích chạy tay. Vì cần lặp lại mỗi ngày và nhiều người cùng xem, nó được chuyển thành một module của GHN Ops Pulse, dùng chung dữ liệu, đăng nhập và phân quyền với dashboard.",
    ],
    decisions: [
      {
        problem: "Dữ liệu hệ thống về bản chất không chứng minh được hành vi này",
        why: "Một danh sách tên người bị nghi mà trình bày như kết luận có thể gây hại cho người không sai. Ngược lại, không đưa danh sách thì không ai biết nên xác minh ở đâu.",
        decision: "Đặt đầu ra là danh sách sàng lọc có phân mức nghi ngờ, kèm quy tắc cố định: không đưa thông tin người nhận vào báo cáo, không diễn giải tín hiệu thành xác nhận đã giữ tiền, việc xác minh thuộc bước độc lập sau đó.",
        term: "Sàng lọc, không kết luận",
      },
      {
        problem: "Một tín hiệu đơn lẻ vừa bỏ sót vừa gây nhiễu",
        why: "Bản đầu lọc theo vài ngưỡng cứng rồi xếp hạng theo khối lượng đơn. Cách đó đẩy người có một đơn rất rõ ràng ra khỏi danh sách, chỉ vì người khác có nhiều đơn hơn.",
        decision: "Kết hợp nhiều tín hiệu độc lập, ví dụ lý do thất bại mâu thuẫn với nhật ký cuộc gọi, hẹn giao lại nhưng ca tiếp theo cách quá xa, vị trí cập nhật lặp lại giữa nhiều đơn. Tin nhắn liên quan được mô hình AI chấm điểm theo lịch, nhưng điểm này chỉ nâng mức cảnh báo tối đa một bậc, không cộng vào điểm gốc, để phần SQL vẫn kiểm tra lại được.",
        term: "Đa tín hiệu thay cho ngưỡng đơn",
      },
      {
        problem: "Danh sách chạy tay chỉ có ích trong tuần đầu",
        why: "Danh sách chỉ hữu dụng khi còn mới. Nếu phải nhờ người phân tích chạy lại mỗi ngày thì sớm muộn sẽ bị bỏ, và người xem không biết số mình đang đọc cũ tới đâu.",
        decision: "Cho truy vấn chạy theo lịch và thay mới toàn bộ dữ liệu trong một giao dịch duy nhất, nên app luôn hiện một bản đầy đủ hoặc bản cũ, không bao giờ hiện nửa chừng. Giao diện ghi thời điểm cập nhật, kể cả khi hôm đó không có đơn nào.",
        term: "Cập nhật nguyên khối theo lịch",
      },
      {
        problem: "Cùng một danh sách, mỗi người cần thấy mức chi tiết khác nhau",
        why: "Người xem thường chỉ cần biết đơn nào cần chú ý. Nếu ai cũng thấy điểm số và nội dung tin nhắn thô, các con số dễ bị hiểu thành kết luận về một người cụ thể.",
        decision: "Chia ba vai trò. Người dùng thường thấy danh sách cần chú ý; vai trò cao hơn thấy phần giải thích điểm và lịch sử các lần chạy; chỉ vai trò cao nhất được ghi nhận kết quả xử lý. Quyền được kiểm tra ở cả giao diện, API và cơ sở dữ liệu.",
        term: "Phân quyền theo vai trò ở nhiều lớp",
      },
    ],
    ownership: {
      owned: [
        "Chuyển mô tả hành vi từ vận hành thành các tín hiệu đo được trên dữ liệu.",
        "Viết truy vấn và đưa kết quả vào cơ sở dữ liệu của app theo lịch.",
        "Xây giao diện rà soát: nhóm theo người giao, bảng đơn, bộ lọc mức cảnh báo, xuất Google Sheet, lịch sử các lần chạy.",
        "Xây phân quyền và luồng ghi nhận xử lý từng trường hợp.",
        "Ghi lại các hướng đã thử và bị loại để người sau không lặp lại.",
      ],
      notOwned: [
        "Xác minh với người nhận và xử lý người giao thuộc vận hành.",
        "Quyết định về từng trường hợp cụ thể không nằm trong phạm vi của danh sách.",
      ],
    },
    results: [
      { label: "Chạy theo lịch", value: "Danh sách tự cập nhật trong dashboard", method: "Truy vấn chạy theo lịch, thay mới nguyên khối; người có quyền ghi nhận kết quả xử lý cho từng trường hợp và lịch sử các lần chạy được lưu.", verified: true },
      { label: "Quy mô bản đầu", value: "Gần 1.900 đơn của 460 người giao trong một lần chạy 10 ngày", method: "Quá rộng để dùng trực tiếp: ba tín hiệu kích hoạt trên khoảng 40% đến 75% số đơn nên điều kiện đạt gần như ai cũng qua. Hướng thu hẹp đã đề xuất, chưa áp dụng.", verified: true },
      { label: "Độ chính xác", value: "Chưa đo được", method: "Chưa có phép đo precision/recall. Một thử nghiệm bắt sớm bằng dữ liệu quá khứ cho kết quả gần ngẫu nhiên (AUC khoảng 0,52) nên không đưa vào sử dụng.", verified: false },
    ],
    reflection: [
      "Danh sách quá dài thì không ai kiểm tra hết, nghĩa là về thực tế nó không phân biệt được ai. Đo tỷ lệ kích hoạt của từng tín hiệu là bước cần làm trước khi tin vào bất kỳ ngưỡng nào.",
      "Hướng bắt sớm không hiệu quả cũng là một kết quả có giá trị. Ghi lại nó giúp người sau khỏi mất công thử lại, và buộc mình nói rõ phần nào đã kiểm chứng, phần nào chưa.",
      "Chuyển từ bài phân tích sang công cụ làm lộ ra những việc mà một lần chạy tay không cần: phân quyền, biết ai đã xử lý đơn nào, và hiển thị rõ ràng khi hôm nay không có đơn nào.",
    ],
    flowHeading: "Từ nhật ký đến danh sách cần xác minh",
    flow: {
      nodes: [
        { id: "orders", label: "Đơn đã gán giao", sublabel: "đang giao hoặc đã kết thúc" },
        { id: "logs", label: "Đối chiếu nhiều nguồn log", sublabel: "trạng thái, cuộc gọi, hành trình, vị trí" },
        { id: "dashboard", label: "Module trong GHN Ops Pulse", sublabel: "mức nghi ngờ, cập nhật theo lịch" },
        { id: "verify", label: "Xác minh và ghi nhận xử lý", sublabel: "người có quyền, ngoài phạm vi danh sách" },
      ],
      edges: [{ from: "orders", to: "logs" }, { from: "logs", to: "dashboard" }, { from: "dashboard", to: "verify" }],
    },
    stack: [
      { group: "Ứng dụng", items: ["React", "Vite", "Supabase"] },
      { group: "Dữ liệu", items: ["SQL", "StarRocks", "Nhật ký cuộc gọi và hành trình đơn"] },
      { group: "Cách làm", items: ["AI-assisted coding", "Ghi chép phiên bản và hướng đã loại"] },
    ],
  },
  {
    slug: "warehouse-attribution",
    tier: "deep",
    homepage: {
      title: "Tìm kho làm đơn hàng giao trễ",
      summary: "Khi sàn thương mại điện tử đòi đền bù vì đơn trễ, xác định kho nào giữ đơn lâu nhất từ lịch sử quét mã của kiện hàng.",
      role: "Giao Hàng Nhanh · Phân tích dữ liệu",
      evidence: "31,3% yêu cầu đền bù tháng 6/2026 chỉ ra được đúng một kho",
      cta: "Xem case truy vết đơn trễ",
    },
    scopeLabel: "Truy vết nguyên nhân đơn trễ bằng SQL",
    title: "Tìm kho làm đơn hàng giao trễ",
    proves: "Biến lịch sử quét mã lộn xộn thành câu trả lời 'kho nào làm trễ', và kiểm tra lại được câu trả lời đó.",
    client: "Giao Hàng Nhanh (GHN)",
    clientNote: "Trong công việc chính, cho hai khách hàng thương mại điện tử lớn",
    role: "Thống nhất quy tắc với bộ phận nghiệp vụ, viết câu truy vấn, giữ bộ ca kiểm tra và tài liệu bàn giao",
    period: "2026",
    oneLiner: "Khi một đơn giao trễ, sàn thương mại điện tử yêu cầu GHN đền bù, và GHN cần biết kho nào giữ đơn lâu nhất để quy trách nhiệm. Mỗi lần kiện hàng được quét mã vào hoặc ra kho đều để lại một dòng lịch sử. Từ đó dựng lại kiện nằm ở kho nào, bao lâu, rồi áp bốn quy tắc theo thứ tự ưu tiên để chọn đúng một kho.",
    accent: "navy",
    keyResult: {
      value: "31,3%",
      label: "yêu cầu đền bù tháng 6/2026 chỉ ra được đúng một kho. Phần còn lại không bị ép vào kho nào mà được ghi rõ lý do.",
      verified: true,
    },
    context: [
      "Một đơn hàng đi từ người gửi tới người nhận thường ghé nhiều kho. Khi nó trễ, sàn thương mại điện tử gửi yêu cầu đền bù, nhưng yêu cầu chỉ nói 'đơn này trễ', không nói trễ ở đâu. Để đối soát, GHN cần chỉ ra một kho cụ thể chịu trách nhiệm, hoặc nói thẳng là chưa đủ dữ liệu để chỉ ra.",
      "Có bốn quy tắc, ví dụ 'kho giao giữ đơn quá số ngày cho phép'. Một đơn có thể vi phạm nhiều quy tắc cùng lúc nhưng chỉ một kho được chọn. Khó ở chỗ lịch sử quét mã không sạch: có kho chỉ làm trung chuyển, có kho xử lý hàng ngoại lệ, có đơn quay lại đúng kho cũ, và có người sửa tay thông tin sau khi đơn đã kết thúc.",
    ],
    decisions: [
      {
        problem: "Một đơn vi phạm nhiều quy tắc, mỗi quy tắc chỉ vào một kho khác nhau",
        why: "Nếu chỉ lấy kết quả đầu tiên tìm thấy thì thứ tự chạy của câu truy vấn vô tình quyết định ai chịu trách nhiệm. Quy tắc nào được ưu tiên là quyết định của nghiệp vụ, không phải của người viết SQL.",
        decision: "Thống nhất với bộ phận nghiệp vụ bảng quy tắc, ngưỡng và thứ tự ưu tiên trước khi viết code. Câu truy vấn đi đúng thứ tự đó và dừng ở quy tắc đầu tiên khớp.",
        term: "Thứ tự ưu tiên do nghiệp vụ quyết định",
      },
      {
        problem: "Hệ thống không có sẵn thông tin 'đơn nằm ở kho này bao lâu'",
        why: "Chỉ có từng dòng 'quét vào kho' và 'quét ra kho'. Phải tự ghép lại, và phải bỏ những kho không thể quy trách nhiệm như kho chỉ trung chuyển hay kho xử lý hàng ngoại lệ. Nếu đơn rời kho rồi quay lại đúng kho đó, hai lần ở lại bị tính thành một.",
        decision: "Ghép các dòng quét mã thành từng lần ở lại một kho, tách riêng chặng giao và chặng hoàn, loại hai nhóm kho kể trên. Giới hạn 'hai lần ở lại bị gộp thành một' được ghi rõ trong tài liệu thay vì để người đọc tự phát hiện.",
        term: "Dựng lại hành trình từ lịch sử quét mã",
      },
      {
        problem: "Một số đơn ra số ngày ở kho là số âm",
        why: "Có người sửa tay thông tin vài tuần sau khi đơn đã kết thúc. Lần sửa muộn này bị coi là lần ở kho cuối cùng, nên kho được chọn là kho sai. Số âm không làm kết luận 'vi phạm' sai, vì so với ngưỡng vẫn ra 'không vi phạm', nên lỗi rất dễ bị bỏ qua.",
        decision: "Bỏ qua mọi dòng lịch sử xảy ra sau thời điểm đơn kết thúc, ngay từ lúc đọc dữ liệu thay vì vá ở bước tính ngày. Nhờ đó mọi bước phía sau tự đúng.",
        term: "Cắt dữ liệu tại thời điểm đơn kết thúc",
      },
      {
        problem: "Tỷ lệ chỉ ra được kho còn thấp, và có cách dễ để làm đẹp con số",
        why: "Chỉ cần coi kho trung chuyển là phương án dự phòng thì tỷ lệ tăng ngay, nhưng sẽ quy trách nhiệm cho kho không làm trễ đơn.",
        decision: "Không nới điều kiện. Đơn nào không chỉ ra được kho thì ghi rõ lý do: thiếu dữ liệu, chưa vào chặng hoàn, hay đủ dữ liệu và thật sự không trễ. Nếu một lý do xuất hiện nhiều, đó là dấu hiệu cần thêm một quy tắc mới.",
        term: "Thà không kết luận còn hơn kết luận sai",
      },
    ],
    ownership: {
      owned: [
        "Ngồi với bộ phận nghiệp vụ để chốt từng quy tắc và thứ tự ưu tiên, rồi ghi lại quyết định.",
        "Viết câu truy vấn: ghép lịch sử quét mã, áp bốn quy tắc, chọn kho và ghi lý do khi chưa chọn được.",
        "Giữ một bộ ca mẫu có đáp án đã biết, và chạy lại toàn bộ sau mỗi lần sửa logic.",
        "Viết tài liệu bàn giao đủ để người khác tiếp tục mà không mất ngữ cảnh.",
      ],
      notOwned: [
        "Ngưỡng và thứ tự ưu tiên là quyết định của bên nghiệp vụ.",
        "Đền bù hay xử lý từng yêu cầu thuộc quy trình riêng.",
      ],
    },
    results: [
      { label: "Tỷ lệ chỉ ra được kho", value: "31,3% yêu cầu đền bù tháng 6/2026", method: "Gồm hai loại trễ (giao trễ và trả hàng trễ) của hai khách hàng thương mại điện tử, theo bốn quy tắc. Phần còn lại được chia theo lý do thay vì gộp thành một con số.", verified: true },
      { label: "Lỗi số ngày âm", value: "28 đơn, đã sửa tại nguồn", method: "Phát hiện khi kiểm tra số ngày ở kho của tháng 6/2026, truy ra do một lần sửa tay sau khi đơn kết thúc. Không đơn nào bị kết luận vi phạm sai, nhưng kho được chọn là kho sai.", verified: true },
      { label: "Giới hạn đã biết", value: "Hai lần ở lại cùng một kho bị tính thành một", method: "Chưa xử lý và đã ghi trong tài liệu bàn giao. Một bước khác lấy thông tin kho từ bản ghi mới nhất cũng có rủi ro tương tự, nhưng chưa gặp trường hợp thật.", verified: true },
    ],
    reflection: [
      "Một con số vô lý là cách nhanh nhất để lộ lỗi dữ liệu. Số ngày âm không làm kết quả cuối sai, nên nếu chỉ kiểm tra kết quả cuối thì lỗi này sẽ ở lại, và chỉ đến khi đổi ngưỡng mới thành sai thật.",
      "Bộ ca mẫu có đáp án bằng lời giữ cho câu truy vấn không trôi. Mỗi lần sửa, dù chỉ thêm một mẫu loại trừ kho, đều chạy lại cả bộ; thêm quy tắc mới thì thêm ca mới riêng, không dùng ca cũ để chứng minh.",
    ],
    flowHeading: "Từ yêu cầu đền bù đến một kho chịu trách nhiệm",
    flow: {
      nodes: [
        { id: "claim", label: "Yêu cầu đền bù vì đơn trễ", sublabel: "giao trễ hoặc trả hàng trễ" },
        { id: "episode", label: "Ghép lịch sử quét mã", sublabel: "thành từng lần ở lại một kho" },
        { id: "rules", label: "Bốn quy tắc theo thứ tự ưu tiên", sublabel: "quy tắc đầu tiên khớp thì thắng" },
        { id: "result", label: "Một kho, hoặc lý do chưa chỉ ra được", sublabel: "kèm mức đủ dữ liệu" },
      ],
      edges: [{ from: "claim", to: "episode" }, { from: "episode", to: "rules" }, { from: "rules", to: "result" }],
    },
    stack: [
      { group: "Dữ liệu", items: ["SQL", "Trino", "Lịch sử quét mã của kiện hàng"] },
      { group: "Cách làm", items: ["AI-assisted coding", "Bộ ca mẫu kiểm tra", "Tài liệu bàn giao"] },
    ],
  },
  {
    slug: "shopee-3pl-performance",
    tier: "brief",
    homepage: {
      title: "Hiệu suất đối tác vận chuyển tại Shopee",
      summary: "Theo dõi KPI và phối hợp với đối tác để xác định khu vực cần cải thiện, theo sát hành động.",
      role: "Shopee · Phân tích & điều phối",
      evidence: "Pickup đúng hạn của Viettel Post: 90,1% → 97,5%",
      cta: "Xem case 3PL",
    },
    scopeLabel: "Phân tích hiệu suất và phối hợp cải tiến",
    title: "Hiệu suất đối tác vận chuyển tại Shopee",
    proves: "Kết hợp báo cáo KPI với nhịp làm việc định kỳ cùng đối tác vận chuyển.",
    client: "Shopee",
    role: "Phân tích KPI, xây báo cáo và điều phối cải tiến cùng đối tác",
    period: "2021 - 2025",
    oneLiner: "Theo dõi hiệu suất vận chuyển, xác định khu vực cần cải thiện và phối hợp với đối tác để triển khai hành động. Pickup đúng hạn của Viettel Post tăng từ 90,1% lên 97,5% trong giai đoạn được báo cáo.",
    accent: "lime",
    keyResult: { value: "90,1% → 97,5%", label: "Pickup đúng hạn của Viettel Post trong giai đoạn làm việc tại Shopee", verified: true, companion: "outlier" },
    context: [
      "Shopee làm việc với nhiều đối tác vận chuyển. Theo dõi hiệu suất cần thống nhất cách đo, nhìn được khác biệt giữa các khu vực và có nhịp phản hồi đủ đều để xử lý vấn đề.",
    ],
    decisions: [
      {
        problem: "Hai bên cần thống nhất số liệu trước khi bàn hành động",
        why: "Khác cách tính KPI hoặc khác phạm vi dữ liệu khiến cuộc họp mất thời gian đối chiếu và khó xác định khu vực cần ưu tiên.",
        decision: "Xây dashboard dùng chung định nghĩa KPI cho nội bộ và đối tác. Duy trì nhịp trao đổi định kỳ, xác định hành động theo khu vực và theo dõi tới khi xử lý.",
        term: "Báo cáo đi cùng cơ chế phối hợp",
      },
      {
        problem: "Trạng thái vận chuyển chưa giải thích rõ tình hình đơn hàng",
        why: "Người mua cần hiểu đơn đang ở đâu và khi nào dự kiến nhận được. Các trạng thái khó hiểu làm phát sinh yêu cầu hỗ trợ.",
        decision: "Phân tích những trạng thái gây thắc mắc và phối hợp điều chỉnh luồng hiển thị thông tin vận chuyển cho người mua.",
        term: "Dùng dữ liệu phản hồi để điều chỉnh thông tin",
      },
    ],
    ownership: {
      owned: [
        "Xây báo cáo KPI bằng SQL và Google Sheets cho nội bộ, đối tác.",
        "Phân tích hiệu suất theo khu vực và thiết lập nhịp trao đổi, theo dõi hành động với đối tác.",
        "Phân tích và phối hợp cải tiến thông tin trạng thái vận chuyển cho người mua.",
      ],
      notOwned: ["Vận hành lấy và giao hàng do đối tác thực hiện. Kết quả cải thiện có đóng góp của các bên tham gia."],
    },
    results: [
      { label: "Pickup đúng hạn của Viettel Post", value: "90,1% → 97,5%", method: "Hai mốc theo số liệu công việc trong giai đoạn tại Shopee, gắn với hoạt động theo dõi KPI và phối hợp cải tiến. Nội dung hiện có chưa kèm kỳ đo cụ thể và tài liệu đối chiếu công khai.", verified: true },
      { label: "Khối lượng làm tay", value: "Ước tính giảm khoảng 30%", method: "Ước tính nhờ công cụ báo cáo tự động bằng Google Apps Script; chưa có đo thời gian riêng để xác nhận mức giảm.", verified: false },
    ],
    reflection: ["Cải thiện hiệu suất cần theo dõi liên tục: thống nhất số liệu, chọn khu vực cần xử lý và theo sát hành động với đối tác. Dashboard hỗ trợ nhịp làm việc đó."],
    flow: null,
    stack: [{ group: "Công cụ", items: ["SQL", "Google Sheets", "Google Apps Script"] }],
  },
];
